site_name: edgartools
theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

nav:
  - Documentation: index.md
  - ownership.md
  - working-with-xbrl.md
  - reference.md
